In [16]:
import re
s= """Founded in 2002, SpaceX’s mission is to enable humans to become a spacefaring civilization and a multplanet 
species by building a self-sustaining city on Mars. In 2008, SpaceX’s Falcon 1 became the first privately 
developed 
liquid-fuel launch vehicle to orbit the Earth."""
re.sub(r"[^\w\s]"," ",s)

'Founded in 2002  SpaceX s mission is to enable humans to become a spacefaring civilization and a multplanet \nspecies by building a self sustaining city on Mars  In 2008  SpaceX s Falcon 1 became the first privately \ndeveloped \nliquid fuel launch vehicle to orbit the Earth '

In [17]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
word_tokenize(s)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['Founded',
 'in',
 '2002',
 ',',
 'SpaceX',
 '’',
 's',
 'mission',
 'is',
 'to',
 'enable',
 'humans',
 'to',
 'become',
 'a',
 'spacefaring',
 'civilization',
 'and',
 'a',
 'multplanet',
 'species',
 'by',
 'building',
 'a',
 'self-sustaining',
 'city',
 'on',
 'Mars',
 '.',
 'In',
 '2008',
 ',',
 'SpaceX',
 '’',
 's',
 'Falcon',
 '1',
 'became',
 'the',
 'first',
 'privately',
 'developed',
 'liquid-fuel',
 'launch',
 'vehicle',
 'to',
 'orbit',
 'the',
 'Earth',
 '.']

In [18]:
import nltk
nltk.download('stopwords') 
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords
stopwords=set(stopwords.words('english'))
words=word_tokenize(s)
wordsFiltered=[]

for w in words:
  if w not in stopwords:
    wordsFiltered.append(w)
  print(wordsFiltered)

['Founded']
['Founded']
['Founded', '2002']
['Founded', '2002', ',']
['Founded', '2002', ',', 'SpaceX']
['Founded', '2002', ',', 'SpaceX', '’']
['Founded', '2002', ',', 'SpaceX', '’']
['Founded', '2002', ',', 'SpaceX', '’', 'mission']
['Founded', '2002', ',', 'SpaceX', '’', 'mission']
['Founded', '2002', ',', 'SpaceX', '’', 'mission']
['Founded', '2002', ',', 'SpaceX', '’', 'mission', 'enable']
['Founded', '2002', ',', 'SpaceX', '’', 'mission', 'enable', 'humans']
['Founded', '2002', ',', 'SpaceX', '’', 'mission', 'enable', 'humans']
['Founded', '2002', ',', 'SpaceX', '’', 'mission', 'enable', 'humans', 'become']
['Founded', '2002', ',', 'SpaceX', '’', 'mission', 'enable', 'humans', 'become']
['Founded', '2002', ',', 'SpaceX', '’', 'mission', 'enable', 'humans', 'become', 'spacefaring']
['Founded', '2002', ',', 'SpaceX', '’', 'mission', 'enable', 'humans', 'become', 'spacefaring', 'civilization']
['Founded', '2002', ',', 'SpaceX', '’', 'mission', 'enable', 'humans', 'become', 'spacefar

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [21]:
# Count Vectorization

from sklearn.feature_extraction.text import CountVectorizer
 
# Create a Vectorizer Object
vectorizer = CountVectorizer()
 
vectorizer.fit(wordsFiltered)
 
# Printing the identified Unique words along with their indices
print("Vocabulary: ", vectorizer.vocabulary_)
 
# Encode the Document
vector = vectorizer.transform(wordsFiltered)
 
# Summarizing the Encoded Texts
print("Encoded Document is:")
print(vector.toarray())


Vocabulary:  {'founded': 12, '2002': 0, 'spacex': 25, 'mission': 19, 'enable': 9, 'humans': 14, 'become': 3, 'spacefaring': 24, 'civilization': 6, 'multplanet': 20, 'species': 26, 'building': 4, 'self': 23, 'sustaining': 27, 'city': 5, 'mars': 18, 'in': 15, '2008': 1, 'falcon': 10, 'became': 2, 'first': 11, 'privately': 22, 'developed': 7, 'liquid': 17, 'fuel': 13, 'launch': 16, 'vehicle': 28, 'orbit': 21, 'earth': 8}
Encoded Document is:
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [28]:
# One Hot Encoding

import numpy as np

words = ['Founded', '2002', ',', 'SpaceX', '’', 'mission', 'enable', 'humans', 'become', 'spacefaring', 'civilization', 'multplanet', 'species', 'building', 'self-sustaining', 'city', 'Mars', '.', 'In', '2008', ',', 'SpaceX', '’', 'Falcon', '1', 'became', 'first', 'privately']
### map each color to an integer
mapping = {}
for x in range(len(wordsFiltered)):
  mapping[wordsFiltered[x]] = x

  
one_hot_encode = []

for c in words:
  arr = list(np.zeros(len(wordsFiltered), dtype = int))
  arr[mapping[c]] = 1
  one_hot_encode.append(arr)

print(one_hot_encode)


[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,

In [8]:
def vectorize(tokens):
    '''Founded in 2002, SpaceX’s mission is to enable humans to become a spacefaring civilization and a multplanet 
species by building a self-sustaining city on Mars. In 2008, SpaceX’s Falcon 1 became the first privately 
developed 
liquid-fuel launch vehicle to orbit the Earth.'''
    vector=[]
    for w in filtered_vocab:
        vector.append(tokens.count(w))
    return vector
def unique(sequence):
    '''Founded in 2002, SpaceX’s mission is to enable humans to become a spacefaring civilization and a multplanet 
species by building a self-sustaining city on Mars. In 2008, SpaceX’s Falcon 1 became the first privately 
developed 
liquid-fuel launch vehicle to orbit the Earth.'''
    seen = set()
    return [x for x in sequence if not (x in seen or seen.add(x))]
#create a list of stopwords.You can import stopwords from nltk too
stopwords=["to","is","a"]
#list of special characters.You can use regular expressions too
special_char=[",",":"," ",";",".","?"]
#Write the sentences in the corpus,in our case, just two 
string1="Don't brush aside your intuition, it's your only true friend."
string2="Always trust your intuition."
#convert them to lower case
string1=string1.lower()
string2=string2.lower()
#split the sentences into tokens
tokens1=string1.split()
tokens2=string2.split()
print(tokens1)
print(tokens2)
#create a vocabulary list
vocab=unique(tokens1+tokens2)
print(vocab)
#filter the vocabulary list
filtered_vocab=[]
for w in vocab: 
    if w not in stopwords and w not in special_char: 
        filtered_vocab.append(w)
print(filtered_vocab)
#convert sentences into vectords
vector1=vectorize(tokens1)
print(vector1)
vector2=vectorize(tokens2)
print(vector2)

["don't", 'brush', 'aside', 'your', 'intuition,', "it's", 'your', 'only', 'true', 'friend.']
['always', 'trust', 'your', 'intuition.']
["don't", 'brush', 'aside', 'your', 'intuition,', "it's", 'only', 'true', 'friend.', 'always', 'trust', 'intuition.']
["don't", 'brush', 'aside', 'your', 'intuition,', "it's", 'only', 'true', 'friend.', 'always', 'trust', 'intuition.']
[1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1]
