In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import minmax_scale
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import minmax_scale
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import minmax_scale
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.preprocessing import MultiLabelBinarizer, StandardScaler
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support
import warnings
warnings.filterwarnings("ignore") 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset.csv", names=['Hour','Immobilized_bus','Broken_Truck','Vehicle_excess','Accident_victim','Running_over','Fire_vehicles','Occurrence_involving_freight','Incident_involving_dangerous_freight','Lack_of_electricity','Fire','Point_of_flooding','Manifestations','Defect_in_the_network_of_trolleybuses','Tree_on_the_road','Semaphore_off','Intermittent_Semaphore','Slowness_in_traffic_percent'])
data

Hour  Immobilized_bus  Broken_Truck  Vehicle_excess  Accident_victim  \
0    07:00                0             0               0                0   
1    07:30                0             0               0                0   
2    08:00                0             0               0                0   
3    08:30                0             0               0                0   
4    09:00                0             0               0                0   
..     ...              ...           ...             ...              ...   
130  18:00                1             0               0                0   
131  18:30                0             0               0                2   
132  19:00                1             0               0                2   
133  19:30                0             4               0                0   
134  20:00                0             0               0                0   

     Running_over  Fire_vehicles  Occurrence_involving_freight  \
0               0              0                             0   
1               0              0                             0   
2               0              0                             0   
3               0              0                             0   
4               0              0                             0   
..            ...            ...                           ...   
130             1              0                             0   
131             0              0                             0   
132             0              0                             0   
133             0              0                             0   
134             0              0                             0   

     Incident_involving_dangerous_freight  Lack_of_electricity  Fire  \
0                                       0                    0     0   
1                                       0                    0     0   
2                                       0                    0     0   
3                                       0                    0     0   
4                                       0                    0     0   
..                                    ...                  ...   ...   
130                                     0                    0     0   
131                                     0                    0     0   
132                                     0                    0     0   
133                                     0                    0     0   
134                                     0                    0     0   

     Point_of_flooding  Manifestations  Defect_in_the_network_of_trolleybuses  \
0                    0               0                                      0   
1                    0               0                                      0   
2                    0               0                                      0   
3                    0               0                                      0   
4                    0               0                                      0   
..                 ...             ...                                    ...   
130                  0               0                                      1   
131                  0               0                                      0   
132                  0               0                                      0   
133                  0               1                                      0   
134                  0               0                                      0   

     Tree_on_the_road  Semaphore_off  Intermittent_Semaphore  \
0                   0              0                       0   
1                   0              0                       0   
2                   0              0                       0   
3                   0              0                       0   
4                   0              0                       0   
..                ...            ...                  

In [ ]:
data = data.drop(columns=['Hour'])
data

Immobilized_bus  Broken_Truck  Vehicle_excess  Accident_victim  \
0                  0             0               0                0   
1                  0             0               0                0   
2                  0             0               0                0   
3                  0             0               0                0   
4                  0             0               0                0   
..               ...           ...             ...              ...   
130                1             0               0                0   
131                0             0               0                2   
132                1             0               0                2   
133                0             4               0                0   
134                0             0               0                0   

     Running_over  Fire_vehicles  Occurrence_involving_freight  \
0               0              0                             0   
1               0              0                             0   
2               0              0                             0   
3               0              0                             0   
4               0              0                             0   
..            ...            ...                           ...   
130             1              0                             0   
131             0              0                             0   
132             0              0                             0   
133             0              0                             0   
134             0              0                             0   

     Incident_involving_dangerous_freight  Lack_of_electricity  Fire  \
0                                       0                    0     0   
1                                       0                    0     0   
2                                       0                    0     0   
3                                       0                    0     0   
4                                       0                    0     0   
..                                    ...                  ...   ...   
130                                     0                    0     0   
131                                     0                    0     0   
132                                     0                    0     0   
133                                     0                    0     0   
134                                     0                    0     0   

     Point_of_flooding  Manifestations  Defect_in_the_network_of_trolleybuses  \
0                    0               0                                      0   
1                    0               0                                      0   
2                    0               0                                      0   
3                    0               0                                      0   
4                    0               0                                      0   
..                 ...             ...                                    ...   
130                  0               0                                      1   
131                  0               0                                      0   
132                  0               0                                      0   
133                  0               1                                      0   
134                  0               0                                      0   

     Tree_on_the_road  Semaphore_off  Intermittent_Semaphore  \
0                   0              0                       0   
1                   0              0                       0   
2                   0              0                       0   
3                   0              0                       0   
4                   0              0                       0   
..                ...            ...                     ...   
130                 0              0                       0   
131      

In [ ]:
print("Missing values for each column:\n", data.isnull().sum())

Missing values for each column:
 Immobilized_bus                          0
Broken_Truck                             0
Vehicle_excess                           0
Accident_victim                          0
Running_over                             0
Fire_vehicles                            0
Occurrence_involving_freight             0
Incident_involving_dangerous_freight     0
Lack_of_electricity                      0
Fire                                     0
Point_of_flooding                        0
Manifestations                           0
Defect_in_the_network_of_trolleybuses    0
Tree_on_the_road                         0
Semaphore_off                            0
Intermittent_Semaphore                   0
Slowness_in_traffic_percent              0
dtype: int64


In [ ]:
print("Total null values",data.isnull().sum().sum())

Total null values 0


In [ ]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
enc_df = pd.DataFrame(enc.fit_transform(data).toarray())
enc_df

0    1    2    3    4    5    6    7    8    9    ...  124  125  126  \
0    1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
130  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
131  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
132  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
133  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
134  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     127  128  129  130  131  132  133  
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
130  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
131  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
132  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
133  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
134  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[135 rows x 134 columns]

In [ ]:
def NormalizeData(data):
  return (data - np.min(data)) / (np.max(data) - np.min(data))
scaled_x = NormalizeData(data)
scaled_x

Immobilized_bus  Broken_Truck  Vehicle_excess  Accident_victim  \
0               0.00           0.0             0.0         0.000000   
1               0.00           0.0             0.0         0.000000   
2               0.00           0.0             0.0         0.000000   
3               0.00           0.0             0.0         0.000000   
4               0.00           0.0             0.0         0.000000   
..               ...           ...             ...              ...   
130             0.25           0.0             0.0         0.000000   
131             0.00           0.0             0.0         0.666667   
132             0.25           0.0             0.0         0.666667   
133             0.00           0.8             0.0         0.000000   
134             0.00           0.0             0.0         0.000000   

     Running_over  Fire_vehicles  Occurrence_involving_freight  \
0             0.0            0.0                           0.0   
1             0.0            0.0                           0.0   
2             0.0            0.0                           0.0   
3             0.0            0.0                           0.0   
4             0.0            0.0                           0.0   
..            ...            ...                           ...   
130           0.5            0.0                           0.0   
131           0.0            0.0                           0.0   
132           0.0            0.0                           0.0   
133           0.0            0.0                           0.0   
134           0.0            0.0                           0.0   

     Incident_involving_dangerous_freight  Lack_of_electricity  Fire  \
0                                     0.0                  0.0   0.0   
1                                     0.0                  0.0   0.0   
2                                     0.0                  0.0   0.0   
3                                     0.0                  0.0   0.0   
4                                     0.0                  0.0   0.0   
..                                    ...                  ...   ...   
130                                   0.0                  0.0   0.0   
131                                   0.0                  0.0   0.0   
132                                   0.0                  0.0   0.0   
133                                   0.0                  0.0   0.0   
134                                   0.0                  0.0   0.0   

     Point_of_flooding  Manifestations  Defect_in_the_network_of_trolleybuses  \
0                  0.0             0.0                                  0.000   
1                  0.0             0.0                                  0.000   
2                  0.0             0.0                                  0.000   
3                  0.0             0.0                                  0.000   
4                  0.0             0.0                                  0.000   
..                 ...             ...                                    ...   
130                0.0             0.0                                  0.125   
131                0.0             0.0                                  0.000   
132                0.0             0.0                                  0.000   
133                0.0             1.0                                  0.000   
134                0.0             0.0                                  0.000   

     Tree_on_the_road  Semaphore_off  Intermittent_Semaphore  \
0                 0.0           0.00                     0.0   
1                 0.0           0.00                     0.0   
2                 0.0           0.00                     0.0   
3                 0.0           0.00                     0.0   
4                 0.0           0.00                     0.0   
..                ...            ...                     ...   
130               0.0           0.00                     0.0   
131      

In [ ]:
X = scaled_x.iloc[:,:-1]
X

Immobilized_bus  Broken_Truck  Vehicle_excess  Accident_victim  \
0               0.00           0.0             0.0         0.000000   
1               0.00           0.0             0.0         0.000000   
2               0.00           0.0             0.0         0.000000   
3               0.00           0.0             0.0         0.000000   
4               0.00           0.0             0.0         0.000000   
..               ...           ...             ...              ...   
130             0.25           0.0             0.0         0.000000   
131             0.00           0.0             0.0         0.666667   
132             0.25           0.0             0.0         0.666667   
133             0.00           0.8             0.0         0.000000   
134             0.00           0.0             0.0         0.000000   

     Running_over  Fire_vehicles  Occurrence_involving_freight  \
0             0.0            0.0                           0.0   
1             0.0            0.0                           0.0   
2             0.0            0.0                           0.0   
3             0.0            0.0                           0.0   
4             0.0            0.0                           0.0   
..            ...            ...                           ...   
130           0.5            0.0                           0.0   
131           0.0            0.0                           0.0   
132           0.0            0.0                           0.0   
133           0.0            0.0                           0.0   
134           0.0            0.0                           0.0   

     Incident_involving_dangerous_freight  Lack_of_electricity  Fire  \
0                                     0.0                  0.0   0.0   
1                                     0.0                  0.0   0.0   
2                                     0.0                  0.0   0.0   
3                                     0.0                  0.0   0.0   
4                                     0.0                  0.0   0.0   
..                                    ...                  ...   ...   
130                                   0.0                  0.0   0.0   
131                                   0.0                  0.0   0.0   
132                                   0.0                  0.0   0.0   
133                                   0.0                  0.0   0.0   
134                                   0.0                  0.0   0.0   

     Point_of_flooding  Manifestations  Defect_in_the_network_of_trolleybuses  \
0                  0.0             0.0                                  0.000   
1                  0.0             0.0                                  0.000   
2                  0.0             0.0                                  0.000   
3                  0.0             0.0                                  0.000   
4                  0.0             0.0                                  0.000   
..                 ...             ...                                    ...   
130                0.0             0.0                                  0.125   
131                0.0             0.0                                  0.000   
132                0.0             0.0                                  0.000   
133                0.0             1.0                                  0.000   
134                0.0             0.0                                  0.000   

     Tree_on_the_road  Semaphore_off  Intermittent_Semaphore  
0                 0.0           0.00                     0.0  
1                 0.0           0.00                     0.0  
2                 0.0           0.00                     0.0  
3                 0.0           0.00                     0.0  
4                 0.0           0.00                     0.0  
..                ...            ...                     ...  
130               0.0           0.00                     0.0  
131              

In [ ]:
Y = scaled_x.iloc[:,-1]
Y

0      0.035
1      0.160
2      0.265
3      0.290
4      0.385
       ...  
130    0.720
131    0.735
132    0.715
133    0.700
134    0.435
Name: Slowness_in_traffic_percent, Length: 135, dtype: float64

In [ ]:
from sklearn.ensemble import RandomForestClassifier
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.3, random_state=0)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((94, 16), (41, 16), (94,), (41,))

In [ ]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(x_train)
y_pred

array([ 0.29262659,  0.30771482,  0.28983291,  0.28983291,  0.33586883,
        0.32581772,  0.66402841,  0.34980281,  0.28983291,  0.29122975,
        0.31698557,  0.28983291,  0.32661055,  1.00581764,  0.23472225,
        0.55299416,  0.42507654,  1.11069141,  0.31581885,  0.30631798,
       -0.09551556,  0.12468829,  0.28983291,  0.43705959,  0.29122975,
        0.28983291,  0.3035243 ,  0.44816278,  0.335     ,  0.28983291,
        0.32661055,  0.32843352,  0.32661055,  0.28983291,  0.28983291,
        0.28983291,  0.28983291,  0.28983291,  0.28983291,  0.33811227,
        0.28983291,  0.32521371,  0.28983291,  0.29122975,  0.33307515,
        0.25931135,  0.28983291,  0.50066331,  0.3035243 ,  0.29402343,
        0.125     ,  0.29122975,  0.23611909,  0.43135609,  0.43558625,
        0.29262659,  0.23611909,  0.28983291,  0.28983291,  0.32521371,
        0.32581772,  0.145815  ,  0.23472225,  0.29122975,  0.28983291,
        0.69406093,  0.28983291,  0.28983291,  0.29122975,  0.30

In [ ]:
y_pred.shape

(94,)

In [ ]:
try:
  test_ConfMat_sklearn = confusion_matrix(y_train,y_pred)
except:
  print(f"Confusion Matrix on testing set: \ncontinuous is not supported")

Confusion Matrix on testing set: 
continuous is not supported


In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_train, y_pred)
print(f"\nMAE: {mae}")


MAE: 0.1300413011388214


In [ ]:
mse = mean_squared_error(y_train,y_pred)
print(f"\nMSE: {mse}")


MSE: 0.02766533724525872


In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_train, y_pred))
rms

0.16632900301889242

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_train, y_pred)
print(f"\nR2 Score: {r2}")


R2 Score: 0.4567313364350919


In [ ]:
poly = PolynomialFeatures()
poly.fit_transform(x_train)

array([[1. , 0. , 0.4, ..., 0. , 0. , 0. ],
       [1. , 0. , 0.8, ..., 0. , 0. , 0. ],
       [1. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [1. , 0. , 0.4, ..., 0. , 0. , 0. ],
       [1. , 0. , 0.2, ..., 0. , 0. , 0. ],
       [1. , 0. , 0. , ..., 0. , 0. , 0. ]])

In [ ]:
try:
  test_ConfMat_sklearn = confusion_matrix(y_train,y_pred)
except:
  print(f"Confusion Matrix on testing set: \ncontinuous is not supported")

Confusion Matrix on testing set: 
continuous is not supported


In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_train, y_pred)
print(f"\nMAE: {mae}")


MAE: 0.1300413011388214


In [ ]:
mse = mean_squared_error(y_train,y_pred)
print(f"\nMSE: {mse}")


MSE: 0.02766533724525872


In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_train, y_pred))
rms

0.16632900301889242

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_train, y_pred)
print(f"\nR2 Score: {r2}")


R2 Score: 0.4567313364350919


In [ ]:
from sklearn.linear_model import Ridge
rdg = Ridge(alpha = 0.5)
rdg.fit(x_train, y_train)
rdg.score(x_train,y_train)

0.4383754039887642

In [ ]:
try:
  test_ConfMat_sklearn = confusion_matrix(y_train,y_pred)
except:
  print(f"Confusion Matrix on testing set: \ncontinuous is not supported")

Confusion Matrix on testing set: 
continuous is not supported


In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_train, y_pred)
print(f"\nMAE: {mae}")


MAE: 0.1300413011388214


In [ ]:
mse = mean_squared_error(y_train,y_pred)
print(f"\nMSE: {mse}")


MSE: 0.02766533724525872


In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_train, y_pred))
rms

0.16632900301889242

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_train, y_pred)
print(f"\nR2 Score: {r2}")


R2 Score: 0.4567313364350919


In [ ]:
from sklearn import linear_model
clf = linear_model.Lasso(alpha=0.1)
clf.fit(x_train,y_train)
print(clf.coef_)
print(clf.intercept_)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0. -0.  0. -0.]
0.3344148936170213


In [ ]:
try:
  test_ConfMat_sklearn = confusion_matrix(y_train,y_pred)
except:
  print(f"Confusion Matrix on testing set: \ncontinuous is not supported")

Confusion Matrix on testing set: 
continuous is not supported


In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_train, y_pred)
print(f"\nMAE: {mae}")


MAE: 0.1300413011388214


In [ ]:
mse = mean_squared_error(y_train,y_pred)
print(f"\nMSE: {mse}")


MSE: 0.02766533724525872


In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_train, y_pred))
rms

0.16632900301889242

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_train, y_pred)
print(f"\nR2 Score: {r2}")


R2 Score: 0.4567313364350919


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.7, random_state=0)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((40, 16), (95, 16), (40,), (95,))

In [ ]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(x_train)
y_pred

array([0.48534267, 0.28967374, 0.27327675, 0.32496288, 0.32496288,
       0.38602701, 0.35669315, 0.23112948, 0.29092132, 0.30731831,
       0.32496288, 1.        , 0.32496288, 0.32496288, 0.30731831,
       0.41900486, 0.42362332, 0.84      , 0.30140582, 0.36838245,
       0.06050016, 0.29553978, 0.28376125, 0.33965733, 0.29553978,
       0.48468746, 0.31318435, 0.12985559, 0.32496288, 0.50233203,
       0.30401493, 0.29553978, 0.22964425, 0.32496288, 0.32496288,
       0.32496288, 0.36838245, 0.22029659, 0.30731831, 0.32496288])

In [ ]:
y_pred.shape

(40,)

In [ ]:
try:
  test_ConfMat_sklearn = confusion_matrix(y_train,y_pred)
except:
  print(f"Confusion Matrix on testing set: \ncontinuous is not supported")

Confusion Matrix on testing set: 
continuous is not supported


In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_train, y_pred)
print(f"\nMAE: {mae}")


MAE: 0.10626442898052639


In [ ]:
mse = mean_squared_error(y_train,y_pred)
print(f"\nMSE: {mse}")


MSE: 0.020302502581499217


In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_train, y_pred))
rms

0.14248685055646088

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_train, y_pred)
print(f"\nR2 Score: {r2}")


R2 Score: 0.5407219146707865


In [ ]:
poly = PolynomialFeatures()
poly.fit_transform(x_train)

array([[1. , 0.5, 0. , ..., 0. , 0. , 0. ],
       [1. , 0. , 0.4, ..., 0. , 0. , 0. ],
       [1. , 0. , 0.2, ..., 0. , 0. , 0. ],
       ...,
       [1. , 0. , 0.4, ..., 0. , 0. , 0. ],
       [1. , 0. , 0.2, ..., 0. , 0. , 0. ],
       [1. , 0. , 0. , ..., 0. , 0. , 0. ]])

In [ ]:
try:
  test_ConfMat_sklearn = confusion_matrix(y_train,y_pred)
except:
  print(f"Confusion Matrix on testing set: \ncontinuous is not supported")

Confusion Matrix on testing set: 
continuous is not supported


In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_train, y_pred)
print(f"\nMAE: {mae}")


MAE: 0.10626442898052639


In [ ]:
mse = mean_squared_error(y_train,y_pred)
print(f"\nMSE: {mse}")


MSE: 0.020302502581499217


In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_train, y_pred))
rms

0.14248685055646088

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_train, y_pred)
print(f"\nR2 Score: {r2}")


R2 Score: 0.5407219146707865


In [ ]:
from sklearn.linear_model import Ridge
rdg = Ridge(alpha = 0.5)
rdg.fit(x_train, y_train)
rdg.score(x_train,y_train)

0.4838899829722503

In [ ]:
try:
  test_ConfMat_sklearn = confusion_matrix(y_train,y_pred)
except:
  print(f"Confusion Matrix on testing set: \ncontinuous is not supported")

Confusion Matrix on testing set: 
continuous is not supported


In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_train, y_pred)
print(f"\nMAE: {mae}")


MAE: 0.10626442898052639


In [ ]:
mse = mean_squared_error(y_train,y_pred)
print(f"\nMSE: {mse}")


MSE: 0.020302502581499217


In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_train, y_pred))
rms

0.14248685055646088

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_train, y_pred)
print(f"\nR2 Score: {r2}")


R2 Score: 0.5407219146707865


In [ ]:
from sklearn import linear_model
clf = linear_model.Lasso(alpha=0.1)
clf.fit(x_train,y_train)
print(clf.coef_)
print(clf.intercept_)

[ 0. -0.  0. -0.  0.  0.  0.  0.  0.  0.  0. -0. -0. -0.  0.  0.]
0.349


In [ ]:
try:
  test_ConfMat_sklearn = confusion_matrix(y_train,y_pred)
except:
  print(f"Confusion Matrix on testing set: \ncontinuous is not supported")

Confusion Matrix on testing set: 
continuous is not supported


In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_train, y_pred)
print(f"\nMAE: {mae}")


MAE: 0.10626442898052639


In [ ]:
mse = mean_squared_error(y_train,y_pred)
print(f"\nMSE: {mse}")


MSE: 0.020302502581499217


In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_train, y_pred))
rms

0.14248685055646088

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_train, y_pred)
print(f"\nR2 Score: {r2}")


R2 Score: 0.5407219146707865


In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/agaricus-lepiota.data",na_values="?",names=['class','cap-shape','cap-surface','cap-color','bruises?','odor','gill-attachment','gill-spacing','gill-size','gill-color','stalk-shape','stalk-root','stalk-surface-above-ring','stalk-surface-below-ring','stalk-color-above-ring','stalk-color-below-ring','veil-type','veil-color','ring-number','ring-type','spore-print-color','population','habitat'])
data

class cap-shape cap-surface cap-color bruises? odor gill-attachment  \
0        p         x           s         n        t    p               f   
1        e         x           s         y        t    a               f   
2        e         b           s         w        t    l               f   
3        p         x           y         w        t    p               f   
4        e         x           s         g        f    n               f   
...    ...       ...         ...       ...      ...  ...             ...   
8119     e         k           s         n        f    n               a   
8120     e         x           s         n        f    n               a   
8121     e         f           s         n        f    n               a   
8122     p         k           y         n        f    y               f   
8123     e         x           s         n        f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [ ]:
print("Missing values for each column:\n", data.isnull().sum())

Missing values for each column:
 class                          0
cap-shape                      0
cap-surface                    0
cap-color                      0
bruises?                       0
odor                           0
gill-attachment                0
gill-spacing                   0
gill-size                      0
gill-color                     0
stalk-shape                    0
stalk-root                  2480
stalk-surface-above-ring       0
stalk-surface-below-ring       0
stalk-color-above-ring         0
stalk-color-below-ring         0
veil-type                      0
veil-color                     0
ring-number                    0
ring-type                      0
spore-print-color              0
population                     0
habitat                        0
dtype: int64


In [ ]:
print("Total null values",data.isnull().sum().sum())

Total null values 2480


In [ ]:
Handling_null_values=data['stalk-root'].fillna(data['stalk-root'].mode()[0], inplace=False)
print(Handling_null_values)

0       e
1       c
2       c
3       e
4       e
       ..
8119    b
8120    b
8121    b
8122    b
8123    b
Name: stalk-root, Length: 8124, dtype: object


In [ ]:
data = data.drop(columns=['veil-type'])
data

class cap-shape cap-surface cap-color bruises? odor gill-attachment  \
0        p         x           s         n        t    p               f   
1        e         x           s         y        t    a               f   
2        e         b           s         w        t    l               f   
3        p         x           y         w        t    p               f   
4        e         x           s         g        f    n               f   
...    ...       ...         ...       ...      ...  ...             ...   
8119     e         k           s         n        f    n               a   
8120     e         x           s         n        f    n               a   
8121     e         f           s         n        f    n               a   
8122     p         k           y         n        f    y               f   
8123     e         x           s         n        f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-above-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        s   
8123            c         b          y  ...                        s   

     stalk-surface-below-ring stalk-color-above-ring stalk-color-below-ring  \
0                           s                      w                      w   
1                           s                      w                      w   
2                           s                      w                      w   
3                           s                      w                      w   
4                           s                      w                      w   
...                       ...                    ...                    ...   
8119                        s                      o                      o   
8120                        s                      o                      o   
8121                        s                      o                      o   
8122                        k                      w                      w   
8123                        s                      o                      o   

     veil-color ring-number ring-type spore-print-color population habitat  
0             w           o         p                 k          s       u  
1             w           o         p                 n          n       g  
2             w           o         p                 n          n       m  
3             w           o         p                 k          s       u  
4             w           o         e                 n          a       g  
...         ...         ...       ...               ...        ...     ...  
8119          o           o         p                 b          c       l  
8120          n           o         p                 b          v       l  
8121          o           o         p                 b          c       l  
8122          w           o         e                 w          v       l  
8123          o           o         p                 o          c       l  

[8124 rows x 22 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
enc_df = pd.DataFrame(enc.fit_transform(data).toarray())
enc_df

0    1    2    3    4    5    6    7    8    9    ...  108  109  110  \
0     0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  0.0   
1     1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
2     1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  0.0   
4     1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
8119  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
8120  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  1.0  0.0   
8121  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
8122  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
8123  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   

      111  112  113  114  115  116  117  
0     0.0  0.0  0.0  0.0  0.0  1.0  0.0  
1     0.0  1.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  1.0  0.0  
4     0.0  1.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
8119  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
8120  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
8121  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
8122  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
8123  0.0  0.0  1.0  0.0  0.0  0.0  0.0  

[8124 rows x 118 columns]

In [ ]:
def NormalizeData(enc_df):
  return (enc_df - np.min(enc_df)) / (np.max(enc_df) - np.min(enc_df))
scaled_x = NormalizeData(enc_df)
scaled_x

0    1    2    3    4    5    6    7    8    9    ...  108  109  110  \
0     0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  0.0   
1     1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
2     1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  0.0   
4     1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
8119  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
8120  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  1.0  0.0   
8121  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
8122  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
8123  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   

      111  112  113  114  115  116  117  
0     0.0  0.0  0.0  0.0  0.0  1.0  0.0  
1     0.0  1.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  1.0  0.0  
4     0.0  1.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
8119  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
8120  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
8121  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
8122  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
8123  0.0  0.0  1.0  0.0  0.0  0.0  0.0  

[8124 rows x 118 columns]

In [ ]:
X = scaled_x.iloc[:,:-1]
X

0    1    2    3    4    5    6    7    8    9    ...  107  108  109  \
0     0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  1.0  0.0   
1     1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  0.0   
2     1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
3     0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  1.0  0.0   
4     1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
8119  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
8120  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  1.0   
8121  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
8122  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
8123  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   

      110  111  112  113  114  115  116  
0     0.0  0.0  0.0  0.0  0.0  0.0  1.0  
1     0.0  0.0  1.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  1.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  1.0  
4     0.0  0.0  1.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
8119  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
8120  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
8121  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
8122  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
8123  0.0  0.0  0.0  1.0  0.0  0.0  0.0  

[8124 rows x 117 columns]

In [ ]:
Y = scaled_x.iloc[:,-1]
Y

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
8119    0.0
8120    0.0
8121    0.0
8122    0.0
8123    0.0
Name: 117, Length: 8124, dtype: float64

In [ ]:
from sklearn.ensemble import RandomForestClassifier
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.3, random_state=0)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((5686, 117), (2438, 117), (5686,), (2438,))

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
lr = LogisticRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
y_prob = lr.predict_proba(x_test)[:, 1]
# Classification report and scoring
print(classification_report(y_test, y_pred))
print(f'ROC AUC score: {roc_auc_score(y_test, y_prob)}')
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2389
         1.0       1.00      1.00      1.00        49

    accuracy                           1.00      2438
   macro avg       1.00      1.00      1.00      2438
weighted avg       1.00      1.00      1.00      2438

ROC AUC score: 1.0
Accuracy Score:  1.0


In [ ]:
y_pred.shape

(2438,)

In [ ]:
try:
  test_ConfMat_sklearn = confusion_matrix(y_train,y_pred)
except:
  print(f"Confusion Matrix on testing set: \ncontinuous is not supported")

Confusion Matrix on testing set: 
continuous is not supported


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('Precision: %.3f' % precision_score(y_test, y_pred))

Precision: 1.000


In [ ]:
print('Recall: %.3f' % recall_score(y_test, y_pred))

Recall: 1.000


In [ ]:
print('F1 Score: %.3f' % f1_score(y_test, y_pred))

F1 Score: 1.000


In [ ]:
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)
clf = clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:

test_ConfMat_sklearn = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix on testing set: \n{test_ConfMat_sklearn}")

Confusion Matrix on testing set: 
[[2389    0]
 [   0   49]]


In [ ]:

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('Precision: %.3f' % precision_score(y_test, y_pred))
print('Recall: %.3f' % recall_score(y_test, y_pred))
print('F1 Score: %.3f' % f1_score(y_test, y_pred))

Precision: 1.000
Recall: 1.000
F1 Score: 1.000


In [ ]:

clf=RandomForestClassifier(n_estimators=2)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:

test_ConfMat_sklearn = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix on testing set: \n{test_ConfMat_sklearn}")

Confusion Matrix on testing set: 
[[2389    0]
 [   0   49]]


In [ ]:

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('Precision: %.3f' % precision_score(y_test, y_pred))
print('Recall: %.3f' % recall_score(y_test, y_pred))
print('F1 Score: %.3f' % f1_score(y_test, y_pred))

Precision: 1.000
Recall: 1.000
F1 Score: 1.000


In [ ]:
acc = []
rf = RandomForestClassifier(bootstrap=True, criterion='gini',
 max_depth=2, max_features='auto', max_leaf_nodes=2, min_samples_leaf=1,
 min_samples_split=2, min_weight_fraction_leaf=0.0,
 n_estimators=10, n_jobs=1, random_state=10)
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)
y_predict_train = rf.predict(x_train)
print("Validation Data Set: ",metrics.accuracy_score(y_test,y_pred)*100)
print("Training Data Set: ",metrics.accuracy_score(y_train,y_predict_train)*100)
acc.append(metrics.accuracy_score(y_test,y_pred))

Validation Data Set:  97.99015586546349
Training Data Set:  97.48505100246219


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=50, random_state=0)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
test_ConfMat_sklearn = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix on testing set: \n{test_ConfMat_sklearn}")

Confusion Matrix on testing set: 
[[2389    0]
 [   0   49]]


In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('Precision: %.3f' % precision_score(y_test, y_pred))
print('Recall: %.3f' % recall_score(y_test, y_pred))
print('F1 Score: %.3f' % f1_score(y_test, y_pred))

Precision: 1.000
Recall: 1.000
F1 Score: 1.000


In [ ]:

from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
acc1=[]
rf1 = GradientBoostingClassifier(n_estimators=42, learning_rate=1.0, max_depth=1, random_state=0)
rf1.fit(x_train, y_train)
y_pred = rf1.predict(x_test)
y_predict_train = rf1.predict(x_train)
print("Validation Data Set: ",metrics.accuracy_score(y_test,y_pred)*100)
print("Training Data Set: ",metrics.accuracy_score(y_train,y_predict_train)*100)
acc1.append(metrics.accuracy_score(y_test,y_pred))

Validation Data Set:  100.0
Training Data Set:  100.0


In [ ]:
test_ConfMat_sklearn = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix on testing set: \n{test_ConfMat_sklearn}")

Confusion Matrix on testing set: 
[[2389    0]
 [   0   49]]


In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('Precision: %.3f' % precision_score(y_test, y_pred))
print('Recall: %.3f' % recall_score(y_test, y_pred))
print('F1 Score: %.3f' % f1_score(y_test, y_pred))

Precision: 1.000
Recall: 1.000
F1 Score: 1.000


In [ ]:
from sklearn.ensemble import RandomForestClassifier
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.7, random_state=0)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((2437, 117), (5687, 117), (2437,), (5687,))

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
lr = LogisticRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
y_prob = lr.predict_proba(x_test)[:, 1]
# Classification report and scoring
print(classification_report(y_test, y_pred))
print(f'ROC AUC score: {roc_auc_score(y_test, y_prob)}')
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      5551
         1.0       1.00      1.00      1.00       136

    accuracy                           1.00      5687
   macro avg       1.00      1.00      1.00      5687
weighted avg       1.00      1.00      1.00      5687

ROC AUC score: 1.0
Accuracy Score:  1.0


In [ ]:
y_pred.shape

(5687,)

In [ ]:
try:
  test_ConfMat_sklearn = confusion_matrix(y_train,y_pred)
except:
  print(f"Confusion Matrix on testing set: \ncontinuous is not supported")

Confusion Matrix on testing set: 
continuous is not supported


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('Precision: %.3f' % precision_score(y_test, y_pred))

Precision: 1.000


In [ ]:
print('Recall: %.3f' % recall_score(y_test, y_pred))

Recall: 1.000


In [ ]:
print('F1 Score: %.3f' % f1_score(y_test, y_pred))

F1 Score: 1.000


In [ ]:
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)
clf = clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:

test_ConfMat_sklearn = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix on testing set: \n{test_ConfMat_sklearn}")

Confusion Matrix on testing set: 
[[5551    0]
 [   0  136]]


In [ ]:

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('Precision: %.3f' % precision_score(y_test, y_pred))
print('Recall: %.3f' % recall_score(y_test, y_pred))
print('F1 Score: %.3f' % f1_score(y_test, y_pred))

Precision: 1.000
Recall: 1.000
F1 Score: 1.000


In [ ]:

clf=RandomForestClassifier(n_estimators=2)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:

test_ConfMat_sklearn = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix on testing set: \n{test_ConfMat_sklearn}")

Confusion Matrix on testing set: 
[[5551    0]
 [   0  136]]


In [ ]:

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('Precision: %.3f' % precision_score(y_test, y_pred))
print('Recall: %.3f' % recall_score(y_test, y_pred))
print('F1 Score: %.3f' % f1_score(y_test, y_pred))

Precision: 1.000
Recall: 1.000
F1 Score: 1.000


In [ ]:
acc = []
rf = RandomForestClassifier(bootstrap=True, criterion='gini',
 max_depth=2, max_features='auto', max_leaf_nodes=2, min_samples_leaf=1,
 min_samples_split=2, min_weight_fraction_leaf=0.0,
 n_estimators=10, n_jobs=1, random_state=10)
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)
y_predict_train = rf.predict(x_train)
print("Validation Data Set: ",metrics.accuracy_score(y_test,y_pred)*100)
print("Training Data Set: ",metrics.accuracy_score(y_train,y_predict_train)*100)
acc.append(metrics.accuracy_score(y_test,y_pred))

Validation Data Set:  97.60858097415156
Training Data Set:  97.7020927369717


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=50, random_state=0)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
test_ConfMat_sklearn = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix on testing set: \n{test_ConfMat_sklearn}")

Confusion Matrix on testing set: 
[[5551    0]
 [   0  136]]


In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('Precision: %.3f' % precision_score(y_test, y_pred))
print('Recall: %.3f' % recall_score(y_test, y_pred))
print('F1 Score: %.3f' % f1_score(y_test, y_pred))

Precision: 1.000
Recall: 1.000
F1 Score: 1.000


In [ ]:

from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
acc1=[]
rf1 = GradientBoostingClassifier(n_estimators=42, learning_rate=1.0, max_depth=1, random_state=0)
rf1.fit(x_train, y_train)
y_pred = rf1.predict(x_test)
y_predict_train = rf1.predict(x_train)
print("Validation Data Set: ",metrics.accuracy_score(y_test,y_pred)*100)
print("Training Data Set: ",metrics.accuracy_score(y_train,y_predict_train)*100)
acc1.append(metrics.accuracy_score(y_test,y_pred))

Validation Data Set:  97.60858097415156
Training Data Set:  97.7020927369717


In [ ]:
test_ConfMat_sklearn = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix on testing set: \n{test_ConfMat_sklearn}")

Confusion Matrix on testing set: 
[[5551    0]
 [ 136    0]]


In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9760858097415157


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('Precision: %.3f' % precision_score(y_test, y_pred))
print('Recall: %.3f' % recall_score(y_test, y_pred))
print('F1 Score: %.3f' % f1_score(y_test, y_pred))

Precision: 0.000
Recall: 0.000
F1 Score: 0.000
